version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: "Asia/Tokyo"
    target-branch: "main"
    open-pull-requests-limit: 10
    reviewers:
      - apusetone
    assignees:
      - apusetone
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
