"""update tables

Revision ID: 0d4d9e50356b
Revises: d8022731883e
Create Date: 2024-04-04 02:26:42.973300

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d4d9e50356b"
down_revision = "d8022731883e"
branch_labels = None
depends_on = None


def upgrade():
    # Preprocess
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_chat_participants_chat_id_chats", "chat_participants", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_chat_participants_chat_id_chats"),
        "chat_participants",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(op.f("uq_users_id"), "users", ["id"])
    # ### end Alembic commands ###

    # Postprocess
    post_upgrade()


def downgrade():
    # Preprocess
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_id"), "users", type_="unique")
    op.drop_constraint(op.f("fk_chat_participants_chat_id_chats"), "chat_participants", type_="foreignkey")
    op.create_foreign_key("fk_chat_participants_chat_id_chats", "chat_participants", "chats", ["chat_id"], ["id"])
    # ### end Alembic commands ###

    # Postprocess
    post_downgrade()


def pre_upgrade():
    # Processing before upgrading the schema
    pass


def post_upgrade():
    # Processing after upgrading the schema
    pass


def pre_downgrade():
    # Processing before downgrading the schema
    pass


def post_downgrade():
    # Processing after downgrading the schema
    pass
